name: Flutter CI - Build Web

# Trigger the workflow on push events to main branch
on:
  push:
    branches:
      - main

# Define environment variables
env:
  FLUTTER_VERSION: "3.27.3" # Specifically using Flutter 3.27.3 as requested

jobs:
  build-web:
    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Flutter with specific version 3.27.3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ env.FLUTTER_VERSION }} # Specific cache key for this version

      # Enable web support
      - name: Enable web support
        run: flutter config --enable-web

      # Get Flutter dependencies
      - name: Get dependencies
        run: flutter pub get

      # Run Flutter analyze
      - name: Analyze code
        run: flutter analyze

      # Run tests (optional, remove if not needed)
      - name: Run tests
        run: flutter test

      # Build web application
      - name: Build Web
        run: flutter build web --release

      # Upload web build artifacts
      - name: Upload Web artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/
          retention-days: 7