name: Flutter CI - Build Web

on:
  push:
    branches:
      - main

env:
  FLUTTER_VERSION: "3.27.3"

jobs:
  build-web:
    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ env.FLUTTER_VERSION }}

      - name: Enable web support
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      # Add custom analysis options
      - name: Create analysis_options.yaml
        run: |
          cat > analysis_options.yaml << 'EOF'
          analyzer:
            errors:
              avoid_print: error  # Treat avoid_print as error instead of info
            exclude:
              - "**/*.g.dart"
          linter:
            rules:
              - avoid_print
          EOF

      # Run analyze with strict checks
      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
        continue-on-error: true # Allow build to continue even if analysis fails

      # Format code to fix some issues automatically
      - name: Format code
        run: flutter format .

      # Run tests with const fix check
      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random

      - name: Build Web
        run: flutter build web --release

      - name: Upload Web artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/
          retention-days: 7