name: Flutter CI - Build Web and Release

on:
  push:
    branches:
      - main

env:
  FLUTTER_VERSION: "3.27.3"

jobs:
  build-web:
    name: Build Flutter Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          cache-key: flutter-${{ env.FLUTTER_VERSION }}

      - name: Verify Flutter installation
        run: flutter --version

      - name: Enable web support
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get
        continue-on-error: true

      - name: Create analysis_options.yaml
        run: |
          cat > analysis_options.yaml << 'EOF'
          analyzer:
            errors:
              avoid_print: error
            exclude:
              - "**/*.g.dart"
          linter:
            rules:
              - avoid_print
          EOF

      - name: Analyze code
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
        continue-on-error: true

      - name: Format code
        run: dart format . || echo "Formatting failed but continuing"
        continue-on-error: true

      - name: Clean project
        run: flutter clean

      - name: Get dependencies after clean
        run: flutter pub get

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random || echo "Tests failed but continuing"
        continue-on-error: true

      - name: Build Web
        run: |
          flutter build web --release || {
            echo "Build failed, trying with verbose output"
            flutter build web --release -v
            exit 1
          }

      - name: Prepare release artifacts
        run: |
          cd build/web
          zip -r ../../web-release.zip .
          cd ../..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.run_number }}"
          name: "Web Release ${{ github.run_number }}"
          body: |
            Automated release of Flutter Web build
            Commit: ${{ github.sha }}
            Built on: ${{ github.event.head_commit.timestamp }}
          draft: false
          prerelease: false
          files: web-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Web artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: build/web/
          retention-days: 7